/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */

/**
 * Loại media
 */
export type AddMediaDtoType = typeof AddMediaDtoType[keyof typeof AddMediaDtoType];


export const AddMediaDtoType = {
  LOGO: 'LOGO',
  WALLPAPER: 'WALLPAPER',
  EMAIL_IMAGE: 'EMAIL_IMAGE',
} as const;
