/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * 5Sport API
 * API documentation for 5Sport authentication and services
 * OpenAPI spec version: 1.0
 */
import type { EventControllerFindAll200Data } from './eventControllerFindAll200Data';

export type EventControllerFindAll200 = {
  status?: string;
  code?: number;
  data?: EventControllerFindAll200Data;
};
